[project]
name = "gymkhana"
version = "1.1.1"
description = "Gym environment for racing, drift, and safety"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    {name = "Teodor Ilie"},
    {name = "Hongrui Zheng"},
    {name = "Renukanandan Tumu"},
    {name = "Luigi Berducci"},
    {name = "Ahmad Amine"},
    {name = "Joseph Auckley"},
    {name = "Matthew O'Kelly"},
    {name = "Aman Sinha"},
]
maintainers = [
    {name = "Teodor Ilie"},
]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "gymnasium>=0.29.1,<0.30.0",
    "numpy>=1.18",
    "pillow>=9.0.1",
    "scipy>=1.7.3",
    "numba>=0.55.2",
    "PyYAML>=5.3.1",
    "pygame>=2.5.2,<3.0.0",
    "opencv-python>=4.9.0.80,<5.0.0.0",
    "requests>=2.31.0,<3.0.0",
]

[project.urls]
Homepage = "https://teoilie.com/"
Repository = "https://github.com/TeoIlie/Gym-Khana"
Documentation = "https://gym-khana.readthedocs.io/en/latest/"

[dependency-groups]
dev = [
    "ruff>=0.15.1,<0.16.0",
    "ipykernel>=6.29.0,<7.0.0",
    "matplotlib>=3.8.2,<4.0.0",
]
train = [
    "scikit-image>=0.25.2,<0.26.0",
    "tensorboard>=2.20.0,<3.0.0",
    "casadi>=3.7.2,<4.0.0",
    "onnxruntime>=1.12,<1.24",
]
render = [
    "pyqtgraph>=0.13.7,<0.14.0",
    "PyQt6>=6.7.1,<7.0.0",
]
inference = [
    "onnx>=1.20.1,<2.0.0",
]

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E203", "E501", "E402", "E721", "E741", "F601", "F841"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["gymkhana"]
